/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author kimer
 */
public class GuiCalculadora extends javax.swing.JFrame {

        int num1,num2,resultado;
    String operacion;
    
    public GuiCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPantalla = new javax.swing.JTextField();
        btnNumUno = new javax.swing.JButton();
        btnNumDos = new javax.swing.JButton();
        btnNumTres = new javax.swing.JButton();
        btnNumCuatro = new javax.swing.JButton();
        btnNumCinco = new javax.swing.JButton();
        btnNumSeis = new javax.swing.JButton();
        btnNumSiete = new javax.swing.JButton();
        btnNumOcho = new javax.swing.JButton();
        btnNumNueve = new javax.swing.JButton();
        btnNumCero = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPantalla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnNumUno.setText("1");
        btnNumUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumUnoActionPerformed(evt);
            }
        });

        btnNumDos.setText("2");
        btnNumDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumDosActionPerformed(evt);
            }
        });

        btnNumTres.setText("3");
        btnNumTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumTresActionPerformed(evt);
            }
        });

        btnNumCuatro.setText("4");
        btnNumCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumCuatroActionPerformed(evt);
            }
        });

        btnNumCinco.setText("5");
        btnNumCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumCincoActionPerformed(evt);
            }
        });

        btnNumSeis.setText("6");
        btnNumSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumSeisActionPerformed(evt);
            }
        });

        btnNumSiete.setText("7");
        btnNumSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumSieteActionPerformed(evt);
            }
        });

        btnNumOcho.setText("8");
        btnNumOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumOchoActionPerformed(evt);
            }
        });

        btnNumNueve.setText("9");
        btnNumNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumNueveActionPerformed(evt);
            }
        });

        btnNumCero.setText("0");
        btnNumCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumCeroActionPerformed(evt);
            }
        });

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnMas.setText("+");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btnMultiplicacion.setText("*");
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });

        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnLimpiar.setText("c");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPantalla)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNumCuatro)
                                .addGap(18, 18, 18)
                                .addComponent(btnNumCinco)
                                .addGap(18, 18, 18)
                                .addComponent(btnNumSeis)
                                .addGap(18, 18, 18)
                                .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNumSiete)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNumOcho)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNumNueve))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNumCero)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnIgual)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLimpiar)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDivision)
                                    .addComponent(btnMultiplicacion)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNumUno)
                                .addGap(18, 18, 18)
                                .addComponent(btnNumDos)
                                .addGap(18, 18, 18)
                                .addComponent(btnNumTres)
                                .addGap(18, 18, 18)
                                .addComponent(btnMas)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumUno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumDos)
                    .addComponent(btnNumTres)
                    .addComponent(btnMas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumCuatro)
                    .addComponent(btnNumCinco)
                    .addComponent(btnNumSeis)
                    .addComponent(btnMenos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumSiete)
                    .addComponent(btnNumOcho)
                    .addComponent(btnNumNueve)
                    .addComponent(btnMultiplicacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumCero)
                    .addComponent(btnIgual)
                    .addComponent(btnDivision)
                    .addComponent(btnLimpiar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
      num1 = Integer.parseInt(lblPantalla.getText());
      lblPantalla.setText("");
      operacion = "+";
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnNumDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumDosActionPerformed
      String IngreseNumero = lblPantalla.getText() + btnNumDos.getText();
      lblPantalla.setText(IngreseNumero);
    }//GEN-LAST:event_btnNumDosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
      lblPantalla.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnNumUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumUnoActionPerformed
      String IngreseNumero = lblPantalla.getText() + btnNumUno.getText();
      lblPantalla.setText(IngreseNumero);
    }//GEN-LAST:event_btnNumUnoActionPerformed

    private void btnNumTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumTresActionPerformed
      String IngreseNumero = lblPantalla.getText() + btnNumTres.getText();
      lblPantalla.setText(IngreseNumero);
    }//GEN-LAST:event_btnNumTresActionPerformed

    private void btnNumCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumCuatroActionPerformed
      String IngreseNumero = lblPantalla.getText() + btnNumCuatro.getText();
      lblPantalla.setText(IngreseNumero);
    }//GEN-LAST:event_btnNumCuatroActionPerformed

    private void btnNumCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumCincoActionPerformed
      String IngreseNumero = lblPantalla.getText() + btnNumCinco.getText();
      lblPantalla.setText(IngreseNumero);
    }//GEN-LAST:event_btnNumCincoActionPerformed

    private void btnNumSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumSeisActionPerformed
      String IngreseNumero = lblPantalla.getText() + btnNumSeis.getText();
      lblPantalla.setText(IngreseNumero);
    }//GEN-LAST:event_btnNumSeisActionPerformed

    private void btnNumSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumSieteActionPerformed
      String IngreseNumero = lblPantalla.getText() + btnNumSiete.getText();
      lblPantalla.setText(IngreseNumero);
    }//GEN-LAST:event_btnNumSieteActionPerformed

    private void btnNumOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumOchoActionPerformed
      String IngreseNumero = lblPantalla.getText() + btnNumOcho.getText();
      lblPantalla.setText(IngreseNumero);
    }//GEN-LAST:event_btnNumOchoActionPerformed

    private void btnNumNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumNueveActionPerformed
      String IngreseNumero = lblPantalla.getText() + btnNumNueve.getText();
      lblPantalla.setText(IngreseNumero);
    }//GEN-LAST:event_btnNumNueveActionPerformed

    private void btnNumCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumCeroActionPerformed
      String IngreseNumero = lblPantalla.getText() + btnNumCero.getText();
      lblPantalla.setText(IngreseNumero);
    }//GEN-LAST:event_btnNumCeroActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
      num1 = Integer.parseInt(lblPantalla.getText());
      lblPantalla.setText("");
      operacion = "-";
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
      num1 = Integer.parseInt(lblPantalla.getText());
      lblPantalla.setText("");
      operacion = "*";
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
      num1 = Integer.parseInt(lblPantalla.getText());
      lblPantalla.setText("");
      operacion = "/";
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
     num2 = Integer.parseInt(lblPantalla.getText());
      if (operacion == "+"){
          resultado = num1 + num2;
          lblPantalla.setText(String.valueOf(resultado));
      }
      else if (operacion == "-"){
          resultado = num1 - num2;
          lblPantalla.setText(String.valueOf(resultado));
      }
      else if (operacion == "*"){
          resultado = num1 * num2;
          lblPantalla.setText(String.valueOf(resultado));
      }
      else if (operacion == "/"){
          resultado = num1 / num2;
          lblPantalla.setText(String.valueOf(resultado));
      }
    }//GEN-LAST:event_btnIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnNumCero;
    private javax.swing.JButton btnNumCinco;
    private javax.swing.JButton btnNumCuatro;
    private javax.swing.JButton btnNumDos;
    private javax.swing.JButton btnNumNueve;
    private javax.swing.JButton btnNumOcho;
    private javax.swing.JButton btnNumSeis;
    private javax.swing.JButton btnNumSiete;
    private javax.swing.JButton btnNumTres;
    private javax.swing.JButton btnNumUno;
    private javax.swing.JTextField lblPantalla;
    // End of variables declaration//GEN-END:variables
}
